"""V8C evidence provenance (`v8c_provenance_v1`) -- second half of P1-G.

THE DEFECT
----------
The freeze builder associated an evidence artifact with the CURRENT code hashes, rather than
proving that artifact was PRODUCED BY those hashes. So an artifact generated by older code
kept satisfying its gate condition after the code beneath it changed: a stale PASS.

THE REPAIR
----------
Every evidence artifact must EMBED the provenance of the process that wrote it:

    producer_git_commit        `git rev-parse HEAD` at write time
    producer_code_hashes       sha256 of every V8C module that took part
    corpus_hash, capability_hash, manifest_hash, ledger_hash

The freeze builder then recomputes those values NOW and requires exact equality. Stale
artifact + changed code => the artifact's provenance no longer matches => FAIL, with the
specific field named.

`stamp()` is what every generator calls; `verify()` is what the gate calls.

ZERO SPEND. Reads no target outcome.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json

from src.research.hypothesis_v8c import defect_ledger as DL
from src.research.hypothesis_v8c import receipt as RCPT

PROVENANCE_VERSION = "v8c_provenance_v1"

PROVENANCE_KEY = "_provenance"


def stamp(*, corpus_hash=None, capability_hash=None, manifest_hash=None, extra=None) -> dict:
    """The provenance block every evidence artifact must carry."""
    p = {"provenance_version": PROVENANCE_VERSION,
         "producer_git_commit": RCPT.git_commit(),
         "producer_code_hashes": RCPT.code_hashes(),
         "ledger_hash": DL.ledger_hash(),
         "corpus_hash": corpus_hash, "capability_hash": capability_hash,
         "manifest_hash": manifest_hash,
         "created_utc": _dt.datetime.now(_dt.timezone.utc).isoformat()}
    if extra:
        p["extra"] = extra
    p["provenance_hash"] = hashlib.sha256(
        json.dumps({k: v for k, v in p.items()}, sort_keys=True,
                   default=str).encode()).hexdigest()
    return p


def verify(artifact: dict, *, expect_corpus=None, expect_capability=None,
           require_current_code=True) -> dict:
    """Does this artifact's embedded provenance match the CURRENT world?

    Returns {ok, mismatches}. A missing provenance block is NOT ok -- an artifact that does
    not say who produced it cannot satisfy a gate condition.
    """
    p = artifact.get(PROVENANCE_KEY)
    if not p:
        return {"ok": False, "mismatches": ["artifact carries no provenance block"]}

    mismatches = []
    if require_current_code:
        now_commit = RCPT.git_commit()
        if p.get("producer_git_commit") != now_commit:
            mismatches.append(
                f"produced at commit {str(p.get('producer_git_commit'))[:12]}, "
                f"current is {now_commit[:12]}")
        now_code = RCPT.code_hashes()
        changed = [m for m, h in now_code.items()
                   if (p.get("producer_code_hashes") or {}).get(m) != h]
        if changed:
            mismatches.append(f"module(s) changed since production: {sorted(changed)}")
    if p.get("ledger_hash") != DL.ledger_hash():
        mismatches.append("defect ledger changed since this artifact was produced")
    if expect_corpus and p.get("corpus_hash") != expect_corpus:
        mismatches.append("corpus hash differs from the current corpus")
    if expect_capability and p.get("capability_hash") != expect_capability:
        mismatches.append("capability hash differs from the current contract")
    return {"ok": not mismatches, "mismatches": mismatches}


def version_stamp() -> dict:
    return {"provenance_version": PROVENANCE_VERSION,
            "repairs": ["P1-G (stale-evidence half)"],
            "embedded_fields": ["producer_git_commit", "producer_code_hashes", "ledger_hash",
                                "corpus_hash", "capability_hash", "manifest_hash"],
            "artifact_without_provenance_can_satisfy_a_gate_condition": False,
            "stale_artifact_plus_changed_code": "FAIL"}
